import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import '../globals.css';
import { useTranslations } from 'next-intl';
import ProvidersWrapper from '@/src/components/ProvidersWrapper/ProvidersWrapper';
import Header from '@/src/components/Header/Header';

const jost = Jost({
  variable: '--font-jost',
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
  fallback: ['arial', 'sans-serif', 'monospace'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: ReactNode;
  params: {
    locale: string;
  };
}

const RootLayout: FC<Props> = ({ children, params: { locale } }) => {
  const t = useTranslations('');

  return (
    <html
      lang={locale}
      data-theme='fantasy'
    >
      <body
        className={`${jost.className} h-[100vh] pt-[25px] flex flex-col gap-[25px] font-jost text-mid`}
      >
        <ProvidersWrapper>
          <Header />
          {children}
          <footer className=''></footer>
        </ProvidersWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
