import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import '../globals.css';
import { AbstractIntlMessages, useMessages, useTranslations } from 'next-intl';
import ProvidersWrapper from '@/src/components/ProvidersWrapper/ProvidersWrapper';
import Header from '@/src/components/Header/Header';
import { Amplify } from 'aws-amplify';
import { amplifyConfig } from '@/src/aws/amplifyConfig';
import GlobalAlert from '@/src/components/GlobalAlert/GlobalAlert';
import TranslationsProvider from '@/src/components/TranslationsProvider/TranslationsProvider';

Amplify.configure(amplifyConfig, {
  ssr: true,
});

const jost = Jost({
  variable: '--font-jost',
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false,
  fallback: ['arial', 'sans-serif', 'monospace'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: ReactNode;
  params: {
    locale: string;
  };
}

const RootLayout: FC<Props> = ({ children, params: { locale } }) => {
  const t = useTranslations('');
  const messages = useMessages();
  const globalAlertMessages = messages['global-alert'] as AbstractIntlMessages;

  console.log('@@@@@messages', messages);
  console.log('@@@@@globalAlertMessages', globalAlertMessages);

  return (
    <html
      lang={locale}
      data-theme='fantasy'
    >
      <body
        className={`${jost.className} h-[100vh] pt-[25px] flex flex-col gap-[25px] font-jost text-mid`}
      >
        <ProvidersWrapper>
          <Header />
          <TranslationsProvider scopedMessages={globalAlertMessages}>
            <GlobalAlert />
          </TranslationsProvider>
          {children}
          <footer className=''></footer>
        </ProvidersWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
